name: "AWS Credentials"

on:
  workflow_call:
    inputs:
      role_arn:
        type: string
        required: true
      aws_region:
        type: string
        required: true

    outputs:
      access_key:
        value: ${{ jobs.aws_creds.outputs.access_key }}
      secret_key:
        value: ${{ jobs.aws_creds.outputs.secret_key }}
      session_token:
        value: ${{ jobs.aws_creds.outputs.session_token }}

jobs:
  aws_creds:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      access_key: ${{ steps.export-creds.outputs.access_key }}
      secret_key: ${{ steps.export-creds.outputs.secret_key }}
      session_token: ${{ steps.export-creds.outputs.session_token }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_arn }}
          aws-region: ${{ inputs.aws_region }}

      - name: Export STS Credentials
        id: export-creds
        run: |
          echo "access_key=${{ env.AWS_ACCESS_KEY_ID }}" >> $GITHUB_OUTPUT
          echo "secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_OUTPUT
          echo "session_token=${{ env.AWS_SESSION_TOKEN }}" >> $GITHUB_OUTPUT
